spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: "jdbc:mysql://localhost:3306/inshorts"
    username: root
    password: root
#  jpa:
#    database-platform: "org.hibernate.dialect.H2Dialect"
#  datasource:
#    url: "jdbc:h2:mem:keshav"
#    driverClassName: "org.h2.Driver"
#    username: "root"
#    password: "root"
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

server:
  port: 8084
  error:
    include-message: always